### ISSUE TITLE
Project does not build on Ubuntu 16.04.01 

### ISSUE THREAD

**Issue by zgriesinger** [gstark31897/Akai#29]
Error message when building on Ubuntu 16.04.01:

Error Message when making by default:
`(xenial)zackery@localhost:~/Desktop/C++/Akai/Akai/client$ make
g++ -c -m64 -pipe -g -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Iobjects -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o objects/messagelist.o messagelist.cpp
messagelist.cpp: In constructor ‘FriendMenu::FriendMenu(QString, QWidget*)’:
messagelist.cpp:9:54: error: no matching function for call to ‘FriendMenu::addAction(const char [5], FriendMenu*, void (FriendMenu::*)())’
     addAction("Call", this, &FriendMenu::callSelected);
                                                      ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMenu:1:0,
                 from messagelist.h:14,
                 from messagelist.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:76:14: note: candidate: QAction* QMenu::addAction(const QString&)
     QAction *addAction(const QString &text);
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:76:14: note:   candidate expects 1 argument, 3 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:77:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&)
     QAction *addAction(const QIcon &icon, const QString &text);
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:77:14: note:   candidate expects 2 arguments, 3 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:78:14: note: candidate: QAction* QMenu::addAction(const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QString &text, const QObject *receiver, const char* member, const QKeySequenc
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:78:14: note:   no known conversion for argument 3 from ‘void (FriendMenu::*)()’ to ‘const char*’
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:79:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QIcon &icon, const QString &text, const QObject *receiver, const char* member
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:79:14: note:   candidate expects 5 arguments, 3 provided
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:39:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QAction:1,
                 from messagelist.h:5,
                 from messagelist.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:538:10: note: candidate: void QWidget::addAction(QAction*)
     void addAction(QAction *action);
          ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:538:10: note:   candidate expects 1 argument, 3 provided
messagelist.cpp:10:62: error: no matching function for call to ‘FriendMenu::addAction(const char [9], FriendMenu*, void (FriendMenu::*)())’
     addAction("Unfriend", this, &FriendMenu::unfriendSelected);
                                                              ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMenu:1:0,
                 from messagelist.h:14,
                 from messagelist.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:76:14: note: candidate: QAction* QMenu::addAction(const QString&)
     QAction *addAction(const QString &text);
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:76:14: note:   candidate expects 1 argument, 3 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:77:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&)
     QAction *addAction(const QIcon &icon, const QString &text);
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:77:14: note:   candidate expects 2 arguments, 3 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:78:14: note: candidate: QAction* QMenu::addAction(const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QString &text, const QObject *receiver, const char* member, const QKeySequenc
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:78:14: note:   no known conversion for argument 3 from ‘void (FriendMenu::*)()’ to ‘const char*’
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:79:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QIcon &icon, const QString &text, const QObject *receiver, const char* member
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:79:14: note:   candidate expects 5 arguments, 3 provided
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:39:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QAction:1,
                 from messagelist.h:5,
                 from messagelist.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:538:10: note: candidate: void QWidget::addAction(QAction*)
     void addAction(QAction *action);
          ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:538:10: note:   candidate expects 1 argument, 3 provided
Makefile:407: recipe for target 'objects/messagelist.o' failed
make: *** [objects/messagelist.o] Error 1
`

Error message after adding "-std=c++11" to the end of line 30 in the Akai.pro file located in Akai/client:

`(xenial)zackery@localhost:~/Desktop/C++/Akai/Akai/client$ make
g++ -c -m64 -pipe -g -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Iobjects -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o objects/messagelist.o messagelist.cpp
messagelist.cpp: In constructor ‘FriendMenu::FriendMenu(QString, QWidget*)’:
messagelist.cpp:9:54: error: no matching function for call to ‘FriendMenu::addAction(const char [5], FriendMenu*, void (FriendMenu::*)())’
     addAction("Call", this, &FriendMenu::callSelected);
                                                      ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMenu:1:0,
                 from messagelist.h:14,
                 from messagelist.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:76:14: note: candidate: QAction* QMenu::addAction(const QString&)
     QAction *addAction(const QString &text);
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:76:14: note:   candidate expects 1 argument, 3 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:77:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&)
     QAction *addAction(const QIcon &icon, const QString &text);
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:77:14: note:   candidate expects 2 arguments, 3 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:78:14: note: candidate: QAction* QMenu::addAction(const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QString &text, const QObject *receiver, const char* member, const QKeySequenc
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:78:14: note:   no known conversion for argument 3 from ‘void (FriendMenu::*)()’ to ‘const char*’
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:79:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QIcon &icon, const QString &text, const QObject *receiver, const char* member
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:79:14: note:   candidate expects 5 arguments, 3 provided
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:39:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QAction:1,
                 from messagelist.h:5,
                 from messagelist.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:538:10: note: candidate: void QWidget::addAction(QAction*)
     void addAction(QAction *action);
          ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:538:10: note:   candidate expects 1 argument, 3 provided
messagelist.cpp:10:62: error: no matching function for call to ‘FriendMenu::addAction(const char [9], FriendMenu*, void (FriendMenu::*)())’
     addAction("Unfriend", this, &FriendMenu::unfriendSelected);
                                                              ^
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QMenu:1:0,
                 from messagelist.h:14,
                 from messagelist.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:76:14: note: candidate: QAction* QMenu::addAction(const QString&)
     QAction *addAction(const QString &text);
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:76:14: note:   candidate expects 1 argument, 3 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:77:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&)
     QAction *addAction(const QIcon &icon, const QString &text);
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:77:14: note:   candidate expects 2 arguments, 3 provided
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:78:14: note: candidate: QAction* QMenu::addAction(const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QString &text, const QObject *receiver, const char* member, const QKeySequenc
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:78:14: note:   no known conversion for argument 3 from ‘void (FriendMenu::*)()’ to ‘const char*’
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:79:14: note: candidate: QAction* QMenu::addAction(const QIcon&, const QString&, const QObject*, const char*, const QKeySequence&)
     QAction *addAction(const QIcon &icon, const QString &text, const QObject *receiver, const char* member
              ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qmenu.h:79:14: note:   candidate expects 5 arguments, 3 provided
In file included from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qaction.h:39:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtWidgets/QAction:1,
                 from messagelist.h:5,
                 from messagelist.cpp:1:
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:538:10: note: candidate: void QWidget::addAction(QAction*)
     void addAction(QAction *action);
          ^
/usr/include/x86_64-linux-gnu/qt5/QtWidgets/qwidget.h:538:10: note:   candidate expects 1 argument, 3 provided
Makefile:407: recipe for target 'objects/messagelist.o' failed
make: *** [objects/messagelist.o] Error 1`

**Comment by gstark31897** [comment]
https://github.com/gstark31897/Akai/blob/master/client/mainwindow.cpp check out how addFriendAction is constructed and look at all the call to connect for it, basically, the QAction object needs to be constructed and the qobject's triggered signal needs to be connected to whatever the current qobject's constructor is using.

I'm not sure how i want to manage the contributors yet, so make a for of the repo, make a branch in you fork (off of develop please) and make a pull request one you're finished. 

Feel free to ask any questions if you get stuck.

**Comment by zgriesinger** [comment]
I edited the project and it now compiles for me on Ubuntu, along with the edits found at https://github.com/zgriesinger/Akai I had to run "sudo apt-get install qtmultimedia5-dev" to install some dependencies to fix audio issues. Functionality may or may not work but at least it compiles.

**Comment by gstark31897** [comment]
So the changes look good so far, you are right in suspecting that it won't work though.

connect(addFriendAction, &QAction::triggered, m_addFriendDialog, &AddFriendDialog::show);

above is an example for connecting a signal to a slot (read up on this in the qt docs if you havent yet)
The initial implementation that you changed was using a shortcut that only wrote out the latter half, basically you have to add the connect call in or the buttons won't do anything when they're pushed.
